CREATE DATABASE Customers


CREATE TABLE Passports
(
	[PassportID] INT PRIMARY KEY NOT NULL IDENTITY(101,1),
	[PassportNumber] NVARCHAR (20) NOT NULL UNIQUE
);
CREATE TABLE Persons
(
	[PersonID] INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	[FirstName] NVARCHAR (20) NOT NULL,
	[Salary] DECIMAL (7,2) NOT NULL,
	[PassportID] INT FOREIGN KEY REFERENCES Passports(PassportID) NOT NULl UNIQUE, 
);

INSERT INTO Passports ([PassportNumber])
VALUES 
('N34FG21B'),
('K65LO4R7'),
('ZE657QP2');

INSERT INTO Persons ([FirstName],[Salary],[PassportID])
VALUES 
('Roberto',43300.00,102),
('Tom',56100.00,103),
('Yana',60200.00,101)